# -*- coding: utf-8 -*-

from __future__ import unicode_literals

# List of supported currencies
CURRENCY_CHOICES = ['CAD', 'CHF', 'DKK', 'EUR', 'FRF', 'GBP', 'HKD', 'JPY', 'NZD', 'SGD', 'THB',
                    'USD', 'ZAR', 'AUD', 'WST', 'VUV', 'TOP', 'SBD', 'PGK', 'MYR', 'KWD', 'FJD']

# AVS Constants
AVS_DONT_CHECK = 0
AVS_CHECK_IF_SUPPORTED = 1
AVS_BLOCKING_CHECK = 2
AVS_NONBLOCKING_CHECK = 3

AVS_CHOICES = [AVS_DONT_CHECK, AVS_CHECK_IF_SUPPORTED, AVS_BLOCKING_CHECK, AVS_NONBLOCKING_CHECK]

# CVC2 Constants
CVC2_MERCHANT_UNSUBMITTED = 0
CVC2_MERCHANT_SUBMITTED = 1
CVC2_CARDHOLDER_ILLEGIBLE = 2
CVC2_CARDHOLDER_NO_CVC = 9

CVC2_CHOICES = [CVC2_MERCHANT_UNSUBMITTED, CVC2_MERCHANT_SUBMITTED, CVC2_CARDHOLDER_ILLEGIBLE, CVC2_CARDHOLDER_NO_CVC]
